import type { NextPage } from "next";
import Head from "next/head";
import GoogleLogin from "../components/googleLoginBtn";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="p-4">
				<h1 className="w-full text-center font-medium text-5xl">
					<span>Shrt.en </span>
					your links
				</h1>
				<GoogleLogin />
			</main>
		</div>
	);
};

export default Home;
